export const RESIDUE_OPTIONS = {
  plastico: [
    { value: "pet_200ml", label: "Garrafa PET 200 ml / 250 ml (Caçulinha / Mini)" },
    { value: "pet_300ml", label: "Garrafa PET 300 ml / 310 ml" },
    { value: "pet_500ml", label: "Garrafa PET 500 ml / 600 ml (Padrão individual)" },
    { value: "pet_1l", label: "Garrafa PET 1 Litro" },
    { value: "pet_1_5l", label: "Garrafa PET 1,25 Litro / 1,5 Litro" },
    { value: "pet_2l", label: "Garrafa PET 2 Litros (Tamanho mais popular)" },
    { value: "pet_2_5l", label: "Garrafa PET 2,25 Litros / 2,5 Litros" },
    { value: "pet_3l", label: "Garrafa PET 3 Litros" },
    { value: "bombona_5l", label: "Garrafão / Bombona 5 Litros / 6 Litros" },
    { value: "bombona_10l", label: "Garrafão / Bombona 10 Litros" },
    { value: "bombona_20l", label: "Garrafão / Bombona 20 Litros" },
    { value: "plastico_outro", label: "Outro tipo de plástico" },
  ],
  metal: [
    { value: "lata_250ml", label: "Lata 220 ml / 250 ml (Slim / Mini)" },
    { value: "lata_269ml", label: "Lata 269 ml (Sleek)" },
    { value: "lata_310ml", label: "Lata 310 ml" },
    { value: "lata_350ml", label: "Lata 350 ml (Lata padrão tradicional)" },
    { value: "lata_355ml", label: "Lata 355 ml (Lata sleek ou importada)" },
    { value: "lata_473ml", label: "Latão 473 ml (Padrão de cerveja)" },
    { value: "lata_500ml", label: "Latão 500 ml" },
    { value: "lata_710ml", label: "Latão 550 ml / 710 ml (King Size)" },
    { value: "metal_outro", label: "Outro tipo de metal" },
  ],
  papel: [
    { value: "papel_a4", label: "Folhas / Sulfite (A4)" },
    { value: "papel_jornal", label: "Jornal / Revistas" },
    { value: "papelao_caixa_pequena", label: "Caixa de Papelão Pequena" },
    { value: "papelao_caixa_media", label: "Caixa de Papelão Média" },
    { value: "papelao_caixa_grande", label: "Caixa de Papelão Grande" },
    { value: "papel_outro", label: "Outro tipo de papel / papelão" },
  ],
  vidro: [
    { value: "vidro_longneck", label: "Garrafa Long Neck (Até 355ml)" },
    { value: "vidro_600ml", label: "Garrafa de Vidro 600ml" },
    { value: "vidro_1l", label: "Garrafa de Vidro 1L" },
    { value: "vidro_pote", label: "Pote de Vidro (Conserva)" },
    { value: "vidro_outro", label: "Outro tipo de vidro" },
  ],
  organico: [
    { value: "organico_restos", label: "Restos de alimentos" },
    { value: "organico_borra", label: "Borra de café / Chá" },
    { value: "organico_podas", label: "Podas e folhas" },
    { value: "organico_outro", label: "Outro orgânico" },
  ],
  eletronico: [
    { value: "eletronico_celular", label: "Celular / Tablet" },
    { value: "eletronico_pc", label: "Computador / Notebook" },
    { value: "eletronico_cabo", label: "Cabos / Carregadores" },
    { value: "eletronico_pilha", label: "Pilhas / Baterias" },
    { value: "eletronico_outro", label: "Outro eletrônico" },
  ],
};
